#include "CoupledHO/CoupledHO.h"
#include "ElectronicStructure/ElectronicStructure.h"
#include "ElectronicStructure/FermiGas.h"
#include "PhysicalSystems/StandardOperatorLibrary.h"
#include "PhysicalSystems/SpinBoson.h"
#include "Molecules/NormalModes.h"
#include "Molecules/NOCl.h"
#include "NDI/NDIHamiltonian.h"
#include "CH3_meanfield/CH3_meanfield.h"
#include "CH3_quasiexact/TrafoCH3Quasiexact.h"
#include "CH3_quasiexact/CH3_quasiexact.h"
#include "schaepers/schaepers.h"
#include "PortfolioOptimization/PortfolioOptimization.h"
/*#include "NOCl/NOCl.h"
#include "CH3_meanfield/CH3_meanfield.h"
#include "CH3_quasiexact/CH3_quasiexact.h"
#include "CH3_quasiexact/TrafoCH3Quasiexact.h"
#include "CoupledHO/multilayer_CHO.h"
#include "GateOperators/GateOperators.h"
#include "Ising/Ising.h"
#include "StandardKEO/StandardKEO.h"
#include "NumberPartitioning/NumberPartitioning.h"
#include "NumberPartitioning/NumberPartitioning_MLO.h"
#include "IntegerFactorisation/IntegerFactorisation.h"
#include "mlSOPnames.h"
#include "scattering.h"

*/

