#include "NOCl/NOClPotential.h"
#include "CDVRModelV/CDVRModelV.h"
#include "CH3_1/CH3Potential.h"
#include "liu_ch4cl/liuch4cl.h"

/*#include "CH3_1/CH3Potential.h"
#include "CH4_schwenke/PES_CH4.h"
#include "CH3Cl/PES_CH3Cl.h"
#include "CH4_SM/PES_CH4SM.h"
#include "CH5+_Bowman/PES_CH5P.h"
#include "PES_HCH4_Zhang/PES_HCH4_Zhang.h"
#include "hehe/hehepotential.h"
#include "OCSHe/OCSHePotential.h"
#include "CDVRModelV2/CDVRModelV2.h"
#include "CDVRModelV3/CDVRModelV.h"
#include "Model1/Model1.h"
#include "LinearVibronicCoupling/LinearVibronicCoupling.h"
*/